% em_custom_settings_example
% example settings file for use for em_saccade_blink_detection
% see defpar in em_saccade_blink_detection.m for more options
% should contain variable **settings** as below!

settings = {...
	'SampleRate', 250, ...
	'SacOnsetVelThr',100,...
	'SacOffsetVelThr',50,...
	'MinSacDuration',0.02,...
	'PosSmoothConvWin','rectwin',...
	'PosSmoothConvLen',0,...
	'PosFilterCutoff',100,...
	'VelFilterCutoff',100,...
	'Plot',true,...
	'OpenFigure',true,...
	};